DROP TABLE IF EXISTS pictures CASCADE;

CREATE TABLE pictures(
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    saved_time TIMESTAMP NOT NULL,
    user_id INTEGER REFERENCES users(id)
);
